name: Rustfmt

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install rustfmt
      run: rustup component add rustfmt
    - name: Check style
      run: cargo fmt --all -- --check --config=merge_imports=true
